# chart-releaser configuration
# https://github.com/helm/chart-releaser

# GitHub owner (org or user)
owner: Mohamed-AboDeif

# GitHub repository name
git-repo: test-helm-repo

# Branch to push the index.yaml to (GitHub Pages source)
git-base-url: https://api.github.com/

# Pages branch
pages-branch: gh-pages

# Skip existing releases (don't fail if tag already exists)
skip-existing: true
